### PR TITLE
Allow Symfony 4.0

### PR DESCRIPTION
**Pull request by theofidry**
Waiting on some third-party deps.

### CODE REVIEW

**Comment by robertfausk** [comment]
Which deps are still missing?

**Comment by theofidry** [comment]
Right now WouterJEloquentBundle: https://travis-ci.org/theofidry/AliceDataFixtures/jobs/297308563

**Comment by robertfausk** [comment]
Created an issue for a new tag https://github.com/wouterj/WouterJEloquentBundle/issues/73
cause its dev-master already supports Symfony 4.0

**Comment by robertfausk** [comment]
WouterJ just released a new tag:)
https://github.com/wouterj/WouterJEloquentBundle/releases/tag/1.0.0-RC1

I fear that some other deps will pop up with a fail after update this one.

**Comment by wouterj** [comment]
Please note that I only agree support for the latest version of each major release. So if you really want 3.1 and 3.2 support, you might need to help maintaining my bundle :)

**Comment by theofidry** [comment]
Yeah, you can see there is the same issue with the other libraries. @wouterj I don't mind but I'm quite busy so a bit unrealistic, I won't commit to maintain all the libraries used in the bridges, neither Eloquent or Doctrine. I just provide the bridge, if it doesn't work for the versions people want then they will have to fix it. I think I'll just skip some tests depending of the deps to handle those situations

**Comment by theofidry** [comment]
Blocked by [phpcr-odm](https://packagist.org/packages/doctrine/phpcr-odm) which requires `symfony/console 3.x`

**Pull request merged**
