### PR TITLE
These methods are not supposed to have return values

### PR DESCRIPTION
**Pull request by olvlvl**
From what I gathered inspecting the code base, these methods have no return value.

### CODE REVIEW

**Comment by theofidry** [comment]
this must have been from a generated phpdoc or copy/paste when I ported that piece of code. As we are in 7.1 could you add the void return type?

**Comment by olvlvl** [comment]
Yep! Will do.

**Comment by olvlvl** [comment]
@theofidry Can you check now?

**Comment by theofidry** [comment]
I would just remove the `@return`, it doesn't provide any value :)

**Comment by olvlvl** [comment]
Here you go :)

**Comment by theofidry** [comment]
Many thanks :)

**Pull request merged**
