### PR TITLE
Allow doctrine/persister:^2

### LINKED ISSUE #147: Error using ObjectManager from a namespace than doesn't exist in doctrine/persister 2.0
https://github.com/theofidry/AliceDataFixtures/blob/95b6f41b6e748306ae27462f1534e6aed797d825/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php#L17

### PR DESCRIPTION
**Pull request by jmsche**
This PR allows both Doctrine Persistence v1 (^1.3.3 IIRC) & v2.

Not sure better could be done as Doctrine packages are not directly required.

Fixes #147.

### CODE REVIEW

**Comment by jmsche** [comment]
This one is tricky. It seems persistence v2 is allowed from doctrine/mongodb-odm v2.1.2, while the 1.x branches did not get the update.

@theofidry Would it be okay to test against v2 instead? This version allows PHP 7.2+ & Symfony 3.4+ which are IMO reasonable requirements.

**Comment by theofidry** [comment]
Yep I think it's ok 👍

**Comment by jmsche** [comment]
Travis failure seems unrelated

**Comment by simPod** [comment]
Hello, any ETA on merge? Thanks

**Comment by jmsche** [comment]
@simPod I think #145 should be fixed & merged so other PRs can pass CI tests

**Comment by franmomu** [comment]
I've created https://github.com/doctrine/DoctrinePHPCRBundle/pull/350, looks like `doctrine/phpcr-bundle` is not compatible yet with `doctrine/persistence` 2.0

**Comment by jmsche** [comment]
Thank you, I was going to have a look tomorrow :)

**Comment by franmomu** [comment]
@jmsche [there has been a release of `doctrine/phpcr-bundle`](https://github.com/doctrine/DoctrinePHPCRBundle/releases/tag/2.1.2)

**Comment by franmomu** [comment]
Looks like we should require `doctrine/mongodb-odm` minimum [2.1.2](https://github.com/doctrine/mongodb-odm/releases/tag/2.1.2) since it is the one allowing `doctrine/persistence` 2.

**Comment by jmsche** [comment]
Yep, I was missing one vendor-bin composer.json :)

**Comment by froozeify** [comment]
Seems all test pass now 😃 

Do you still need some help on this or you are waiting it to be merged ?

**Comment by jmsche** [comment]
Waiting for a merge :)

**Comment by theofidry** [comment]
Thank you @jmsche!

**Comment by franmomu** [comment]
Can you please (@theofidry ) tag a new release whenever you can? Thanks!

**Comment by jmsche** [comment]
@theofidry Somehow the tag didn't make it to packagist :/ See https://packagist.org/packages/theofidry/alice-data-fixtures

**Comment by theofidry** [comment]
Updated

**Pull request merged**
