### PR TITLE
Don't invoke 'clear()' anymore

### PR DESCRIPTION
**Pull request by olvlvl**
Fixes https://github.com/theofidry/AliceDataFixtures/issues/51

### CODE REVIEW

**Comment by olvlvl** [comment]
There's a failure on one of the jobs, but it doesn't seem related to my changes:

https://travis-ci.org/theofidry/AliceDataFixtures/jobs/275663984

```
[Could not open file /home/travis/build/theofidry/AliceDataFixtures/vendor-bin/doctrine_mongodb/bin/phpunit]

[Failed to compile /home/travis/build/theofidry/AliceDataFixtures/vendor-bin/doctrine_mongodb/bin/phpunit, cannot run]
```

**Comment by theofidry** [comment]
No indeed, I'll have to investigate it separately

**Comment by theofidry** [comment]
Thanks :)

**Comment by olvlvl** [comment]
@theofidry Do you think you could tag a v1.0.0-beta.6?

**Comment by theofidry** [comment]
Maybe over the weekend, I would like to do a review of the remaining issues

**Comment by olvlvl** [comment]
That would be great! Thanks.

**Pull request merged**
