### PR TITLE
Fix PHPUnit deprecations

### PR DESCRIPTION
**Pull request by franmomu**
Replaces https://github.com/theofidry/AliceDataFixtures/pull/145, it adds @jmsche [suggestion](https://github.com/theofidry/AliceDataFixtures/pull/145#issuecomment-692077614) and requires explicitly `doctrine/persistance`.

I also added conflict with `zendframework/zend-code` < 3.3.1 because of https://github.com/zendframework/zend-code/pull/158 and with `doctrine/orm` < 2.6.3 because of https://github.com/doctrine/orm/pull/7325.

### CODE REVIEW

**Comment by theofidry** [comment]
>  7x: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

I'm not sure from where this is coming from but looks easy to fix hopefully?

**Comment by jmsche** [comment]
The only place in the package's code where I found `continue` is there: https://github.com/theofidry/AliceDataFixtures/blob/master/src/Bridge/Symfony/DependencyInjection/Compiler/DeprecateServicesPass.php

Couldn't find any place using `switch`, so my guess is, it's located in vendors :/

**Comment by franmomu** [comment]
Let me try if it's `doctrine/orm`

**Comment by franmomu** [comment]
I added conflict with `zendframework/zend-code` < 3.3.1 because of https://github.com/zendframework/zend-code/pull/158 and with `doctrine/orm` < 2.6.3 because of https://github.com/doctrine/orm/pull/7325.

**Comment by jmsche** [comment]
Congrats @franmomu :)

**Comment by theofidry** [comment]
Thank you very much @franmomu

**Pull request merged**
