### PR TITLE
Add documentation for auto primary key doctrine generators

### LINKED ISSUE #40: [Doctrine] Support for disabling ID generators if ID provided in fixture
If you have a Doctrine custom PK generator like [ramsey/uuid-doctrine](https://github.com/ramsey/uuid-doctrine), you can't set that auto-PK from fixture because [it's getting overwritten by Doctrine](http://stackoverflow.com/questions/5301285/explicitly-set-id-with-doctrine-when-using-auto-strategy) after you've set it.

If provided in fixture, It would be nice to disable Doctrine auto-PK generator and use the one provided from fixture.

### PR DESCRIPTION
**Pull request by theofidry**
Closes #40

### CODE REVIEW

**Comment by umpirsky** [comment]
Is it possible to override ID generator for all entities at once (instead of doing it on per entity basis)?

**Comment by theofidry** [comment]
As it's done automatically, if you set the ID for all entities then the ID generator will be overridden for all

**Comment by umpirsky** [comment]
I don't want to set ID, but ID generator, like:

```php
$dummyMetadata = $this->manager->getMetadataFactory()->getMetadataFor(Dummy::class);

// Disable the auto generation of the foreign key
$dummyMetadata->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
$dummyMetadata->setIdGenerator(new MyIdGenerator());
```

But not only for `Dummy::class`, I want to do that for all entities.

**Comment by theofidry** [comment]
oh, yeah not out of the box. But you should be able to easily overwrite the existing persister loader to do that. Maybe it can be refactored a bit to make it easier

**Comment by theofidry** [comment]
Actually overriding https://github.com/theofidry/AliceDataFixtures/blob/master/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php seems more correct. You can override it by creating your own class and registering a service with the same ID.

`@final` tags are here to say this was not intended to be extended. But it can be removed if the use case is valid, I just do this by default to ease the refactoring.

**Comment by umpirsky** [comment]
Thanks @theofidry!

Do you think that making `ORMAssignedGenerator` a service and injecting it into `ObjectManagerPersister` would make sense? It would ease overriding. I can submit PR if you are willing to merge such contrib?

**Comment by umpirsky** [comment]
@theofidry [This](https://github.com/hautelook/AliceBundle/blob/master/src/Loader/DoctrineOrmLoader.php#L169-L177) makes it even harder to override.

**Comment by theofidry** [comment]
>Do you think that making ORMAssignedGenerator a service and injecting it into ObjectManagerPersister would make sense? It would ease overriding. I can submit PR if you are willing to merge such contrib?

that or making the persister extendable and putting some logic in a method to make it easy to override.  I'm fine either way.

>This makes it even harder to override.

Indeed this should be in a factory instead :/

**Comment by umpirsky** [comment]
Fixed in https://github.com/theofidry/AliceDataFixtures/pull/91. Thanks!

**Pull request merged**
