### PR TITLE
Keep the ids specified for entities by end users

### PR DESCRIPTION
**Pull request by benja-M-1**
This should solve the problem found in #153 
It also allows to mix fixtures with and without provided ids.

@VincentLanglet would you mind to test this PR with your fixtures set?
And @yakobe could you test with yours?

I checked on my project and this works.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
> @VincentLanglet would you mind to test this PR with your fixtures set?

It seems to fix my issue #153

**Comment by yakobe** [comment]
Firstly, thank you @benja-M-1 for trying to find a solution that satisfies all of these different situations 👍.

Unfortunately this does not work for me yet. It causes a weird error like this: 

```
In AbstractMySQLDriver.php line 128:

  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'INSERT INTO user_group (name, description, roles) VALUES (?, ?, ?)' with params [null, "Demo User Group Name", "Demo Description", "[]"]:

  SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
```

I'm trying to investigate what the cause could be. Maybe it has something to do with the fact that we have multiple "waves" of fixtures that run something like this (simplified for readability):

```php
$initialObjects = $this->fixtureLoader->load($initialFixtureFiles);
$this->fixtureLoader->load(
    $demoFixtureFiles,
    [],
    $initialObjects, // <-- these initial objects were created in the first wave above.
    PurgeMode::createNoPurgeMode()
);

```

@benja-M-1 any ideas how it could be causing this error?

**Comment by benja-M-1** [comment]
@yakobe Do you use composable identifier for the user_group model?

**Comment by VincentLanglet** [comment]
Hi

Reading this https://github.com/theofidry/AliceDataFixtures/issues/151#issuecomment-732819507
I feel like @yakobe  already had issues with this library before the first @benja-M-1 PR

So this PR currently doesn't solve everything but seems better than the 1.3.0 version AND fix the regression introduced in 1.3.1. It could be a good first step.

Anyway something should be done to fix the current solution @theofidry :
- either reverting https://github.com/theofidry/AliceDataFixtures/pull/152
- either merging this

**Comment by theofidry** [comment]
Let's hope it does it then, thank you @benja-M-1

**Comment by VincentLanglet** [comment]
Thanks @theofidry ; do you mind to create a release 1.3.2 ? :)

**Comment by theofidry** [comment]
I would like to get the CI green first... I merged this one because the failure is unrelated

**Comment by yakobe** [comment]
@VincentLanglet I understand that you want it to work for you, but this change just swaps who it does not work for (i.e. now it works for you and not for me). 

It would be nicer if we could have worked together to find a solution that would work for all and in the meantime we can "fix" our versions to a specific release that works for us. That is what I will need to do until we can find such a solution. Not critical, just a little unfair.

**Comment by VincentLanglet** [comment]
> @VincentLanglet I understand that you want it to work for you, but this change just swaps who it does not work for (i.e. now it works for you and not for me).

I want this to work at least as good as it was at the 1.3.0.
I proposed two solutions: merging this or reverting the original PR.

The 1.3.1. introduce a BC-break. First thing to do is to fix the BC-break ; there is nothing related to me or you.

> It would be nicer if we could have worked together to find a solution that would work for all and in the meantime we can "fix" our versions to a specific release that works for us. That is what I will need to do until we can find such a solution. Not critical, just a little unfair.

You're welcome to answer to benja-M-1 questions in order to solve the situation. @yakobe 
> Do you use composite identifier for the user_group model?
> I may need your model to dig what could cause the issue. Can you make a public github repo are post here the model (with relations if any)?

**Comment by yakobe** [comment]
No need to be condescending. As I said, I understood your motives, it just would have been nicer to find a solution that favors us all.

> I want this to work at least as good as it was at the 1.3.0.

Totally understand that. We all want it to work.

> First thing to do is to fix the BC-break

Yeah... it was fixing the one introduced in 1.1.0. Now we just have a different BC break.

> You're welcome to answer to benja-M-1 questions in order to solve the situation. @yakobe

I was getting to it. Now this is merged it will need to go on a new issue rather than here.

**Comment by yakobe** [comment]
@benja-M-1 Sorry for the delay. The `user_group` model has a normal generated primary key:

```
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private ?int $id = null;
```

Not sure if that helps. I think it happens because our fixtures use existing db objects like i mention [above](https://github.com/theofidry/AliceDataFixtures/pull/155#issuecomment-740219186). I guess we are maybe using that feature differently from it's original intention and therefore I'm going to see if i can re-arrange our fixtures so that it's not needed. With a bit of luck it should be possible and we can live with the change.

**Comment by benja-M-1** [comment]
@yakobe Would it be possible to setup a repo that contains enough code to
reproduce the bug? Or even better providing a failing test case?

I would be glad to help as much as I can.

Le lun. 14 déc. 2020 à 17:17, Jake Bishop <notifications@github.com> a
écrit :

**Comment by yakobe** [comment]
@benja-M-1 thanks for the follow up. I really appreciate your will to help.

Our repo is a bit of a monster and as with most closed source projects i cannot reveal too much 😕. Setting up a new project might take a while because i'm not sure familiar with all the components. 

You dont know of a "basic" project that is used for testing this repo do you? If so, i could take that as starting point and attempt to break it in a similar way 😅.

**Comment by yakobe** [comment]
@benja-M-1 fyi i have managed to re-structure our tests so that this problem no-longer occurs for me. Hopefully we were the only ones with this weird side-effect and therefore a fix doesn't need any priority 😺 .

**Comment by VincentLanglet** [comment]
> @benja-M-1 fyi i have managed to re-structure our tests so that this problem no-longer occurs for me. Hopefully we were the only ones with this weird side-effect and therefore a fix doesn't need any priority 😺 .

Good news 😁

**Comment by benja-M-1** [comment]
This is a great news! Glad to read that :) hopefully nobody will complain
about this issue anymore 😅


Le mar. 15 déc. 2020 à 18:14, Vincent Langlet <notifications@github.com> a
écrit :

**Pull request merged**
