### PR TITLE
Fix MySQL platform detection

### PR DESCRIPTION
**Pull request by colinodell**
When purging data, this library attempts to detect whether MySQL is used by checking the "driver"; if so, it temporarily disables foreign key constraints.

However, some libraries (like Sentry's Symfony bundle) decorate that driver to add functionality like tracing the SQL statements being executed.  Because these decorators do not extend from `AbstractMySQLDriver` this library fails to disable foreign key checks when decorated drivers are being used.  See https://github.com/getsentry/sentry-symfony/issues/503 for an example of this.

I propose that this library should check the **platform** instead of the **driver**.  Platforms describe **what type of database** is being used, versus the drivers which provide **how to interface with that database**.  Because we care more about the "what" and not the how, and because platforms are far less likely to be overridden/decorated, this change should avoid compatibility issues with other libraries and custom code.

### CODE REVIEW

**Review by theofidry — APPROVED** [review]

**Comment by ste93cry** [comment]
What's the status of this?

**Comment by epitre** [comment]
Hi @colinodell 
How did you manage to work around it without this pr merged ?

@theofidry Do you think there's a lot to do to have it released ?

Bests

**Comment by colinodell** [comment]
We're using cweagans/composer-patches to apply this PR's diff (add `.diff` to the URL)

**Review by theofidry — APPROVED** [review]

**Comment by theofidry** [comment]
I am not sure why the build gets cancelled :/ The patch looks good to me though

**Comment by epitre** [comment]
> I am not sure why the build gets cancelled :/ The patch looks good to me though

can you relaunch the builds, so you can merge it ?

**Comment by epitre** [comment]
> I am not sure why the build gets cancelled :/ The patch looks good to me though

maybe that's why : 
```
PHP Fatal error:  Uncaught RuntimeException: Setup tool cannot configure caches without doctrine/cache 1.11 or symfony/cache. Please add an explicit dependency to either library. in /home/runner/work/AliceDataFixtures/AliceDataFixtures/vendor-bin/doctrine/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php:184
```

**Comment by epitre** [comment]
it seems that the problem is in master :/
https://github.com/theofidry/AliceDataFixtures/runs/3713999940

**Comment by colinodell** [comment]
This is caused by a minor BC break in Doctrine: https://github.com/doctrine/orm/blob/2.9.x/UPGRADE.md#minor-bc-break-setup-tool-needs-cache-implementation

**Pull request merged**
