### PR TITLE
accept arrays of entities

### PR DESCRIPTION
**Pull request by titiyoyo**
linked to https://github.com/theofidry/AliceDataFixtures/issues/206

### CODE REVIEW

**Review by theofidry — COMMENTED** [review]
Thanks for much for the PR! Would it be possible to have a test for it as well? I think there should be a few fixtures available to serve as a base or examples

**Comment by titiyoyo** [comment]
Sure, but I get an error while running `make test` 

```
make[1]: Entering directory '/home/terence/Documents/projects/AliceDataFixtures'
docker-compose exec -T mysql mysql --user=root --password=password --port=3307 -e "DROP DATABASE IF EXISTS fidry_alice_data_fixtures; CREATE DATABASE fidry_alice_data_fixtures;"
mysql: [Warning] Using a password on the command line interface can be insecure.
make[1]: Leaving directory '/home/terence/Documents/projects/AliceDataFixtures'
vendor-bin/doctrine/bin/doctrine orm:schema-tool:create
PHP Fatal error:  Uncaught Error: Class "Doctrine\Common\Annotations\AnnotationRegistry" not found in /home/terence/Documents/projects/AliceDataFixtures/vendor-bin/doctrine/vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php:165
Stack trace:
#0 /home/terence/Documents/projects/AliceDataFixtures/vendor-bin/doctrine/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(75): Doctrine\ORM\Configuration->newDefaultAnnotationDriver()
#1 /home/terence/Documents/projects/AliceDataFixtures/tests/Bridge/Doctrine/autoload.php(23): Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration()
#2 /home/terence/Documents/projects/AliceDataFixtures/cli-config.php(40): require_once('...')
#3 /home/terence/Documents/projects/AliceDataFixtures/vendor-bin/doctrine/vendor/doctrine/orm/bin/doctrine.php(41): require('...')
#4 /home/terence/Documents/projects/AliceDataFixtures/vendor-bin/doctrine/vendor/doctrine/orm/bin/doctrine(4): include('...')
#5 /home/terence/Documents/projects/AliceDataFixtures/vendor-bin/doctrine/bin/doctrine(117): include('...')
#6 {main}
  thrown in /home/terence/Documents/projects/AliceDataFixtures/vendor-bin/doctrine/vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php on line 165
make: *** [Makefile:104: test_doctrine_bridge] Error 255

```

**Comment by alexislefebvre** [comment]
@titiyoyo `doctrine/annotations` was an indirect dependency, Symfony dropped it, see #204. You can try to `require` it.

**Comment by titiyoyo** [comment]
I get all sorts of errors when running `make test`, looks like the tests need some fixing

**Comment by titiyoyo** [comment]
I pushed another commit

**Comment by YoannJuhel** [comment]
@theofidry  Is it possible to merge this PR soon ? We need this fix for migrating symfony from 5 to 6

**Comment by LoicBoursin** [comment]
Hello, I am having the exact same problem reported in the issue linked to this PR. Using the fix from titiyoyo, it worked perfectly, and I'll need it to upgrade to SF6. Thanks :)

**Comment by theofidry** [comment]
Merged via #218. Thanks for the work!

**Pull request closed without merging**
